/*
 * HousingRentalSystem
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.DependencyInjection;
using System.Collections.Generic;
using System.Security.Cryptography;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Extensions;
using Xunit;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Tests the dependency injection.
    /// </summary>
    public class DependencyInjectionTest
    {
        private readonly IHost _hostUsingConfigureWithoutAClient =
            Host.CreateDefaultBuilder([]).ConfigureApi((context, services, options) =>
            {

            })
            .Build();

        private readonly IHost _hostUsingConfigureWithAClient =
            Host.CreateDefaultBuilder([]).ConfigureApi((context, services, options) =>
            {

                options.AddApiHttpClients(client => client.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS));
            })
            .Build();

        private readonly IHost _hostUsingAddWithoutAClient =
            Host.CreateDefaultBuilder([]).ConfigureServices((host, services) =>
            {
                services.AddApi(options =>
                {

                });
            })
            .Build();

        private readonly IHost _hostUsingAddWithAClient =
            Host.CreateDefaultBuilder([]).ConfigureServices((host, services) =>
            {
                services.AddApi(options =>
                {

                    options.AddApiHttpClients(client => client.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS));
                });
            })
            .Build();

        /// <summary>
        /// Test dependency injection when using the configure method
        /// </summary>
        [Fact]
        public void ConfigureApiWithAClientTest()
        {
            var propertiesApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<IPropertiesApi>();
            Assert.True(propertiesApi.HttpClient.BaseAddress != null);

            var tenantsApi = _hostUsingConfigureWithAClient.Services.GetRequiredService<ITenantsApi>();
            Assert.True(tenantsApi.HttpClient.BaseAddress != null);
        }

        /// <summary>
        /// Test dependency injection when using the configure method
        /// </summary>
        [Fact]
        public void ConfigureApiWithoutAClientTest()
        {
            var propertiesApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<IPropertiesApi>();
            Assert.True(propertiesApi.HttpClient.BaseAddress != null);

            var tenantsApi = _hostUsingConfigureWithoutAClient.Services.GetRequiredService<ITenantsApi>();
            Assert.True(tenantsApi.HttpClient.BaseAddress != null);
        }

        /// <summary>
        /// Test dependency injection when using the add method
        /// </summary>
        [Fact]
        public void AddApiWithAClientTest()
        {
            var propertiesApi = _hostUsingAddWithAClient.Services.GetRequiredService<IPropertiesApi>();
            Assert.True(propertiesApi.HttpClient.BaseAddress != null);
            
            var tenantsApi = _hostUsingAddWithAClient.Services.GetRequiredService<ITenantsApi>();
            Assert.True(tenantsApi.HttpClient.BaseAddress != null);
        }

        /// <summary>
        /// Test dependency injection when using the add method
        /// </summary>
        [Fact]
        public void AddApiWithoutAClientTest()
        {
            var propertiesApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<IPropertiesApi>();
            Assert.True(propertiesApi.HttpClient.BaseAddress != null);

            var tenantsApi = _hostUsingAddWithoutAClient.Services.GetRequiredService<ITenantsApi>();
            Assert.True(tenantsApi.HttpClient.BaseAddress != null);
        }
    }
}
