/*
 * HousingRentalSystem
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing TenantsApi
    /// </summary>
    public sealed class TenantsApiTests : ApiTestsBase
    {
        private readonly ITenantsApi _instance;

        public TenantsApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<ITenantsApi>();
        }

        /// <summary>
        /// Test CreateTenant
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateTenantAsyncTest()
        {
            Client.Option<Tenant> tenant = default!;
            var response = await _instance.CreateTenantAsync(tenant);
            var model = response.Created();
            Assert.IsType<Tenant>(model);
        }

        /// <summary>
        /// Test DeleteTenant
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeleteTenantAsyncTest()
        {
            int id = default!;
            await _instance.DeleteTenantAsync(id);
        }

        /// <summary>
        /// Test GetTenantById
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetTenantByIdAsyncTest()
        {
            int id = default!;
            var response = await _instance.GetTenantByIdAsync(id);
            var model = response.Ok();
            Assert.IsType<Tenant>(model);
        }

        /// <summary>
        /// Test GetTenants
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GetTenantsAsyncTest()
        {
            var response = await _instance.GetTenantsAsync();
            var model = response.Ok();
            Assert.IsType<List<Tenant>>(model);
        }

        /// <summary>
        /// Test UpdateTenant
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UpdateTenantAsyncTest()
        {
            int id = default!;
            Client.Option<Tenant> tenant = default!;
            var response = await _instance.UpdateTenantAsync(id, tenant);
            var model = response.Ok();
            Assert.IsType<Tenant>(model);
        }
    }
}
