/*
 * HousingRentalSystem
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Tenant
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TenantTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Tenant
        //private Tenant instance;

        public TenantTests()
        {
            // TODO uncomment below to create an instance of Tenant
            //instance = new Tenant();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Tenant
        /// </summary>
        [Fact]
        public void TenantInstanceTest()
        {
            // TODO uncomment below to test "IsType" Tenant
            //Assert.IsType<Tenant>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'PropertyId'
        /// </summary>
        [Fact]
        public void PropertyIdTest()
        {
            // TODO unit test for the property 'PropertyId'
        }

        /// <summary>
        /// Test the property 'RentalStartDate'
        /// </summary>
        [Fact]
        public void RentalStartDateTest()
        {
            // TODO unit test for the property 'RentalStartDate'
        }

        /// <summary>
        /// Test the property 'RentalEndDate'
        /// </summary>
        [Fact]
        public void RentalEndDateTest()
        {
            // TODO unit test for the property 'RentalEndDate'
        }

        /// <summary>
        /// Test the property 'Property'
        /// </summary>
        [Fact]
        public void PropertyTest()
        {
            // TODO unit test for the property 'Property'
        }
    }
}
